services:
  app:
    build:
      context: .
      args:
        - NODE_ENV=development
      dockerfile: Dockerfile
    env_file:
      - .env.example
    environment:
      - NODE_ENV=development
    ports:
      - "3000:3000"
    volumes:
#      - ./src:/app/src
#      - .:/app
#      - ./public:/app/public
#      - /app/node_modules
      - ./src:/app/src
      - /app/node_modules
      - ./public:/app/public
      - /app/.next
    container_name: nextjs
    restart: unless-stopped

  nginx:
    image: nginx
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.local.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app