# kubernetes/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: nextjs-config
data:
  NEXT_PUBLIC_POSTHOG_KEY: "phc_Ia2HOj8pQOWA4kZki2qe8P4hqvWQNSriXopVQMfHy7F"
  NEXT_PUBLIC_POSTHOG_HOST: "https://us.i.posthog.com"
  POSTHOG_API_KEY: "phc_Ia2HOj8pQOWA4kZki2qe8P4hqvWQNSriXopVQMfHy7F"
  POSTHOG_HOST: "https://us.i.posthog.com"