# kubernetes/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextjs-app
  labels:
    app: nextjs-app
    version: "${IMAGE_TAG}"
  annotations:
    kubernetes.io/change-cause: "Deployed version ${IMAGE_TAG} at $(date)"
spec:
  replicas: 2
  revisionHistoryLimit: 10  # Store history for 10 deployments
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: nextjs-app
  template:
    metadata:
      labels:
        app: nextjs-app
        version: "${IMAGE_TAG}"
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "3000"
        prometheus.io/path: "/metrics"
    spec:
      containers:
        - name: nextjs
          image: ${ECR_REGISTRY}/${ECR_REPOSITORY}:${IMAGE_TAG}
          ports:
            - name: http
              containerPort: 3000
          env:
            - name: NODE_ENV
              value: production
            - name: NEXT_PUBLIC_POSTHOG_KEY
              valueFrom:
                configMapKeyRef:
                  name: nextjs-config
                  key: NEXT_PUBLIC_POSTHOG_KEY
            - name: NEXT_PUBLIC_POSTHOG_HOST
              valueFrom:
                configMapKeyRef:
                  name: nextjs-config
                  key: NEXT_PUBLIC_POSTHOG_HOST
          resources:
            limits:
              cpu: "1"
              memory: "512Mi"
            requests:
              cpu: "200m"
              memory: "256Mi"
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5