# kubernetes/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: nextjs-app
  labels:
    app: nextjs-app
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "3000"
spec:
  selector:
    app: nextjs-app
  ports:
    - port: 80
      targetPort: http
      name: http
  type: ClusterIP