name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  ci_job:
    name: Continuous Integration
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/previous-releases

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: Install dependencies
        run: |
          echo "Installing dependencies"
          npm ci
      - name: Build
        run: |
          echo "Building"
          npm run build --if-present
#      - name: Test
#        run: |
#          echo "Testing"
#          npm test
        env:
          CI: true
  cd_job:
    name: Continuous Deployment
    needs: ci_job
    runs-on: ubuntu-latest
#    if: github.event_name == 'push' && github.ref == 'refs/heads/' + github.event.repository.default_branch
    if: github.event_name == 'push' && github.ref == format('refs/heads/{0}', github.event.repository.default_branch)
    steps:
      - name: Set up SSH key
        env:
          PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          echo "$PRIVATE_KEY" > private_key.pem
          chmod 400 private_key.pem
          sudo apt-get install -y sshpass
#        currently awscli is preinstalled on the runner
#      - name: Install AWS CLI
#        run: sudo apt-get install -y awscli
      - name: Deploy to AWS EC2
        env:
          EC2_INSTANCE_IP_ADDRESS: ${{ secrets.EC2_INSTANCE_IP_ADDRESS }}
          ENV_FILE: ${{ secrets.ENV_FILE }}
          GIT_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
        run: |
          ssh -i private_key.pem -o StrictHostKeyChecking=no ec2-user@"$EC2_INSTANCE_IP_ADDRESS" "\
          cd /var/www/nextjs-blog; \
          echo '### Backing up environment file...'; \
          if [ -e .env ]; then \
            echo '### Environment file exists, backing up...'; \
            cp -f .env .env.backup; \
          else \
            echo '### No environment file found...'; \
            echo '### Creating .env file...'; \
            touch .env; \
          fi; \
          echo \"$ENV_FILE\" > .env; \
          echo 'Environment file updated successfully'; \
          if [ ! -d /var/www/nextjs-blog/.git ]; then \
            echo '### Cloning the repository to /var/www...'; \
            cd /var/www; \
            git clone https://x-access-token:$GIT_TOKEN@github.com/hsm2k3/nextjs-blog; \
            echo '### Cloned the repository.'; \
            echo '### Creating ssl-dhparams.pem...'; \
            openssl dhparam -out /var/www/nextjs-blog/ssl-dhparams.pem 2048; \
            if [ -e /var/www/nextjs-blog/ssl-dhparams.pem ]; then \
              echo '### Created ssl-dhparams.pem...'; \
            fi; \
          else \
            echo '### Refreshing repository code...'; \
            cd /var/www/nextjs-blog; \
            echo '### Try git pull first, which is safer...'; \
            if git pull origin main; then \
              echo '### Repository updated successfully with git pull'; \
            else \
              echo '### Git pull failed, trying hard reset...'; \
              echo '### Backing up environment file...'; \
              echo '### Force fetch and reset as fallback...'; \
              git fetch origin; \
              git reset --hard origin/main; \
            fi; \
            chmod +x /var/www/nextjs-blog/deployment/update_server.sh; \
            echo '### Updating server...'; \
            ./deployment/update_server.sh; \
          fi; \
          echo '### Taking down current images...'; \
          cd /var/www/nextjs-blog && sudo docker-compose down; \
          echo '### Setting build variables...'; \
          export BUILD_DATE=\$(date -u +'%Y-%m-%dT%H:%M:%SZ'); \
          export GIT_COMMIT=\$(git rev-parse HEAD); \
          echo '### Rebuilding containers with fresh code...'; \
          docker-compose up -d --force-recreate --no-deps --build; \
          echo '### Waiting for containers to be healthy...'; \
          sleep 30; \
          if docker ps | grep -q 'nextjs' && docker ps | grep -q 'nginx'; then \
            echo '### Containers are running, cleaning up unused volumes...'; \
            docker system prune -af --volumes; \
            echo '### Volume cleanup complete'; \
          else \
            echo '### Container startup check failed, skipping volume cleanup'; \
          fi"